name: .NET Core

on: [push]

env:
  configuration: Release
  platform: x86

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    
    - name: Chocolatey Action
      uses: crazy-max/ghaction-chocolatey@v1.0.2
      with:
        # Arguments to pass to Chocolatey
        args: install windows-sdk-10-version-1903-all 
    
    - name: Build
      run: msbuild ContosoExpenses.sln /p:Configuration=${{env.configuration}} /p:Platform=${{env.platform}} /restore /p:AppxPackageDir=d:\a\ContosoExpenses-GitHub\ContosoExpenses-GitHub\AppPackages /p:AppxBundlePlatforms=${{env.platform}} /p:AppxBundle=Never /p:UapAppxPackageBuildMode=SideloadOnly /p:AppxPackageSigningEnabled=false
    
    
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: MSIX
        # Directory containing files to upload
        path: AppPackages
    
