name: .NET Core

on: [push]

env:
  configuration: Release
  platform: x86
  signTool: '"C:\\Program Files (x86)\\Windows Kits\\10\bin\\10.0.18362.0\\x86\\signtool.exe"'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    
    - name: Build
      run: msbuild ContosoExpenses.sln /p:Configuration=${{env.configuration}} /p:Platform=${{env.platform}} /restore /p:AppxPackageDir=${{github.workspace}}\AppPackages /p:AppxBundlePlatforms=${{env.platform}} /p:AppxBundle=Never /p:UapAppxPackageBuildMode=SideloadOnly /p:AppxPackageSigningEnabled=false
            
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: MSIX
        # Directory containing files to upload
        path: AppPackages
        
  deploy:
    needs: build
    name: Deploy Packages
    runs-on: windows-latest
    steps:
      - name: Download Package artifact
        uses: actions/download-artifact@master
        with:
          name: MSIX
        
      - name: Get certificate
        id: cert_file
        uses: timheuer/base64-to-file@master
        with:
          fileName: 'certfile.pfx'
          encodedString: ${{ secrets.signingCert }}
      
      - name: Sign package 
        run: | 
          $signToolPath = ${{ env.signTool }}
          Get-ChildItem -recurse -path "MSIX" -Include *.msix | ForEach-Object {
            $msixPath = $_.FullName
            & ${{env.signTool}} sign /f "${{ steps.cert_file.outputs.filePath }}" /tr http://timestamp.digicert.com /p ${{ secrets.signingPassword}} /td sha256 /fd sha256 $msixPath
          }
